name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      run: dotnet restore ActividadParcial/ActividadParcial/ActividadParcial.csproj

    - name: Build project
      run: dotnet build ActividadParcial/ActividadParcial/ActividadParcial.csproj --configuration Release

    - name: Run tests
      run: dotnet test ActividadParcial/ActividadParcial/ActividadParcial.csproj --configuration Release
